### ISSUE TITLE
Test failures

### ISSUE THREAD

**Issue by agrimm** [dbashford/textract#108] opened 2016-12-23 03:37 UTC
I tried running `npm test` on an OSX machine, and got a number of failures. Some of them are due to failing to installing dependencies, or the dependencies not working properly, but some of the tests involve applications that are installed on OSX by default, according to the README.

Should these test failures be occurring?

Unfortunately, I couldn't disable inline diffing by mocha. Hopefully you'll be able to extract the text! :)

[textract npm test results 20161223b.docx](https://github.com/dbashford/textract/files/670258/textract.npm.test.results.20161223b.docx)

    Last login: Fri Dec 23 14:20:59 on ttys014
    Andrews-Air:textract agrimm$ npm test

    > textract@2.0.0 test /Users/agrimm/rails/github/textract
    > mocha

    (node) child_process: options.customFds option is deprecated. Use options.stdio instead.

      ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
      ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․

      ✖ 13 of 169 tests failed:

      1) textract fromBufferWithName will doc files:
          
          actual expected
          
          " Word Specification Sample Working Draft 04, 16 August 2002 Document identifier: wd-spectools-word-ssa"
          
      

      2) textract fromBufferWithMime will doc files:
          
          actual expected
          
          " Word Specification Sample Working Draft 04, 16 August 2002 Document identifier: wd-spectools-word-ssa"
          
      

      3) textract for .rtf files will extract text from rtf files:
          
          actual expected
          
          "bit of hidden text. So we're going to end this paragraph here and go on to a nice little list: I"
          
      

      4) textract for .rtf files will extract when there are spaces in the name:
          
          actual expected
          
          "bit of hidden text. So we're going to end this paragraph here and go on to a"""
          
      

      5) textract for .rtf files will extract text from actual rtf files with lines left in:
          
          actual expected
          
          "bit of hidden text. So we're going to end this paragraph here and go on to a nice littlittle list:\n\n Item 1\n I"
          
      

      6) textract for .doc files will extract text from actual doc files:
          
          actual expected
          
          " Word Specification Sample Working Draft 04, 16 August 2002 Document identifier: wd-spectools-word-ssa"
          
      

      7) textract for .doc files will not extract text from text files masquerading as doc files:
         AssertionError: expected 'not a doc' to be null
      

      8) textract for .doc files will extract text from large .doc:
          
          actual expected
          
          3267058
          
      

      9) textract for .doc files will extract text preserving line breaks without word wrap:
          
          actual expected
          
          213
          
      

      10) textract for .dxf files will extract text from actual dxf files:
         AssertionError: expected [Error: Error for type: [[ image/vnd.dxf ]], file: [[ /Users/agrimm/rails/github/textract/test/files/dxf.dxf ]], extractor for type exists, but failed to initialize. Message: INFO: 'drawingtotext' does not appear to be installed, so textract will be unable to extract DXFs.] to be null
      

      11) textract for image files will extract text from GIF files:
         AssertionError: expected [Error: Error extracting [[ testphoto.gif ]], exec error: Command failed: /bin/sh -c tesseract /Users/agrimm/rails/github/textract/test/files/testphoto.gif /var/folders/8j/z1k4ygx13_qbk4j843f2h0gc0000gn/T/textract/testphoto quiet
    Tesseract Open Source OCR Engine v3.04.01 with Leptonica
    Error in pixReadMemGif: function not present
    Error in pixReadMem: gif: no pix returned
    Error during processing.
    ] to be null
      

      12) textract for image files will extract text from language-d files:
         AssertionError: expected [Error: Error extracting [[ chi.png ]], exec error: Command failed: /bin/sh -c tesseract /Users/agrimm/rails/github/textract/test/files/chi.png /var/folders/8j/z1k4ygx13_qbk4j843f2h0gc0000gn/T/textract/chi -l chi_sim quiet
    Tesseract Open Source OCR Engine v3.04.01 with Leptonica
    Error opening data file /usr/local/Cellar/tesseract/3.04.01_2/share/tessdata/chi_sim.traineddata
    Please make sure the TESSDATA_PREFIX environment variable is set to the parent directory of your "tessdata" directory.
    Failed loading language 'chi_sim'
    Tesseract couldn't load any languages!
    Could not initialize tesseract.
    ] to be null
      

      13) fromUrl tests will properly extract files from sites with extensions that are misleading:
          
          actual expected
          
          " HBWashington 1276State - 2015-16 Test 1 \" Test 2 \" Test 3 Legislature HomeBill \"Summary Senate2017-2018 \"2015-2016 House2013-2014 of2011-2012 Representatives2009-2010 \" C2007-20"
          
      

    npm ERR! Test failed.  See above for more details.
    Andrews-Air:textract agrimm$

**Comment by rosarioj** [comment] 2016-12-23 06:53
Tested in two computers, OSX 10.9.5 and 10.11.6, both showed the same set of errors.

I looked into the first error.  textutil output starts with a newline character, and following the code textract converts it to a space and then trim removes the space.  If you look at the actual error, it is exactly what you expect if you removed the first character.

**Comment by dbashford** [comment] 2016-12-23 11:47
Yeah doc and rtf differences are likely due to those tests being based on antiword rather than textutil. I have a mac, but I disable the use of textutil locally before running the tests. I find it more important to cover what most folks are using.

And it would be difficult to get different tools to extract exactly the same.

When I get a chance I will verify that this is the case and close this out.

**Comment by dbashford** [comment] 2016-12-23 14:29
Make the following changes to your local textract when testing.  Confirmed that the tests are geared towards output from antiword. Some tests still fail, looking into those, but only 3 worth looking at locally for me.

![image](https://cloud.githubusercontent.com/assets/581127/21455928/2d8c6524-c8f2-11e6-83f9-1eb8e2173695.png)

**Closed** 2016-12-23 14:29 UTC

**Comment by dbashford** [comment] 2016-12-23 16:36
I've [added a little chunk to the README](https://github.com/dbashford/textract#running-tests-on-a-mac) discussion testing.

I've also addressed all the tests.  I do not have dxf extraction installed locally, so that one test fails, otherwise they all pass.

Thanks!
