### ISSUE TITLE
Specify catdoc directory

### ISSUE THREAD

**Issue by lam3r4370** [dbashford/textract#76] opened 2016-02-25 12:32 UTC
Is it possible to specify a directory, in which catdoc(or pdftotext) are located?

It seems that it is possible, but catdoc is executed using `catdoc = spawn( "catdoc", catdocArgs );` 
It'd be nice if there was a `options.dir` and using it like this ` catdoc = spawn(options.dir + "/catdoc", catdocArgs );`

**Comment by dbashford** [comment] 2016-02-25 16:15
That is a good idea.  No reason why I can't do that.  I think we would need to have, for instance, `catdocDir` instead of just dir, because there are a few things (you mentioned pdftotext) that would need to get included.

I am prepping another release for the next few days, I will include this.  Thanks!

**Comment by lam3r4370** [comment] 2016-02-25 16:42
I saw later that pdftotext is using another module so it maybe won't be that easy.
btw I've forked and added it to the doc extractor, should I make a pull request?

Thanks for  the great work!

**Comment by dbashford** [comment] 2016-02-25 16:46
yeah, so textract wraps pdf-text-extract, another node_module, but THAT module module provides the ability to provide the path to pdftotext

**Comment by lam3r4370** [comment] 2016-02-25 16:47
Oh, that's great then! :)

**Comment by dbashford** [comment] 2016-02-25 16:49
The problem is that the published version of that repo is `1.4.1` while master is on `1.3.1`.  So you have to go into a tagged version to see that the option is there. =)

https://github.com/nisaacson/pdf-text-extract/blob/v1.4.1/index.js#L4

**Comment by dbashford** [comment] 2016-05-18 14:53
Closing this out in lieu of #84

**Closed by dbashford** 2016-05-18 14:53 UTC
