### ISSUE TITLE
catdoc windows support

### ISSUE THREAD

**Issue by konsumer** [dbashford/textract#72] opened 2016-02-15 21:15 UTC
I have [windows catdoc](http://blog.brush.co.nz/2009/09/catdoc-windows/) installed and in my path.

When I use textextract for a doc file, I get this error:

```
Error: Error for type: [[ application/msword ]], file: [[ CENSORED_PATH\tmp\44687595103httpwwwpowerballcompowerballtestpbdoc.doc ]], extractor for type exists, but failed to initialize. Messge: INFO: 'catdoc' does not appear to be installed, so textract will be unable to extract DOCs.
```

**Comment by dbashford** [comment] 2016-02-16 14:47
If you were to locate this code: https://github.com/dbashford/textract/blob/master/lib/extractors/doc.js#L15 in your `node_modules` and log the command + args it is trying to execute, then try it yourself, hopefully you might see what the issue is?  All textract is doing is essentially shelling out to run catdoc from your command line.  This is usually one of two problems: 1) something is wrong with the path and catdoc cannot be located or 2) something is wrong with textract's Windows catdoc integration and the error you are seeing is misleading.

I could probably whip up a quick node script to test this out if you needed it.

**Comment by konsumer** [comment] 2016-02-17 03:28
The algorithm is fairly simple in the source of catdoc. Maybe I should just implement a pure javascript version. It seems like that'd be handy for other things (like client-side parsing of word docs.) I'll keep ya posted.

**Comment by dbashford** [comment] 2016-02-17 03:44
I would definitely love to able to remove that external dependency.

**Comment by dbashford** [comment] 2016-02-25 16:18
I see you got started on this.  Any luck?

FWIW, there's a good chance that including [this functionality](https://github.com/dbashford/textract/issues/76) as a feature would help solve your problem.

**Comment by dbashford** [comment] 2016-05-18 14:51
I intend to remove catdoc and use antiword & unrtf to do what it does. catdoc is too problematic for me to dev with (doesn't work on Mac) and isn't supported any longer.  Will leave this open in the even antiword/unrtf do not work out.

**Comment by dbashford** [comment] 2016-06-08 14:43
Closing this out as with `2.0.0` and d54a1bb96251f6837b121cdab8c11d74cf0bbb7d catdoc isn't used.

**Closed by dbashford** 2016-06-08 14:43 UTC
